#spring:
#  datasource:
#    url: jdbc:postgresql://leferi-prod-msg-psql-rds.ciaxaq6zlbgl.ap-northeast-2.rds.amazonaws.com:5432/postgres
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    database: postgresql
#    properties:
#      hibernate:
#        format_sql: true
#        show-sql: true
#        use_sql_comments: true
#    hibernate:
#      ddl-auto: validate



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


